dist: bionic

language: python

cache:
  directories:
    - $HOME/.cache/spark-versions

env:
  global:
    - HYPEROPT_FMIN_SEED=3
    - SPARK_VERSION=3.0.1
    - NUMPY_VERSION=1.18.1
    - IPYTHON=ipython[all]
matrix:
  include:
    - python: 3.7
    - python: 3.8

services:
  - mongodb

before_script:
  - sleep 15 # mongo takes time to start
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
  - sudo apt-get remove ipython
  - pip install --upgrade pip setuptools wheel coveralls pytest
  - pip install --only-binary=numpy,scipy numpy==$NUMPY_VERSION scipy $IPYTHON pyspark==$SPARK_VERSION
  - pip install -e '.[MongoTrials, SparkTrials, ATPE, dev]'
script:
  - pytest
after_success:
  - coveralls
